version: "3.7"

services:
  # Immo service
  ezloc-immo:
    container_name: ezloc-immo-service
    image: ${REPOSITORY:-ntdtfr}/ezloc-immo:${IMAGE_VERSION:-latest}
    build:
      context: .
      # cache_from:
      #   - alpine:latest
      args:
        # BUILD_IMAGE: maven:3.6-jdk-8-alpine
        BUILD_IMAGE: maven:3.6.3-jdk-11-slim
        # RUNTIME_IMAGE: openjdk:8-jre-alpine
        RUNTIME_IMAGE: openjdk:11-jre-stretch
        IMAGE_VERSION: ${IMAGE_VERSION:-1.0.0}
        SONAR_ENABLED: ${SONAR_ENABLE:-false}
        SONAR_URL: ${SONAR_URL:-http://sonar:9000}
        # SONAR_ORGANIZATION:
        # SONAR_USERNAME: admin
        # SONAR_PASSWORD: admin
        # SONAR_BRANCH:
    environment:
      # Enable/disable Jaeger
      JAEGER_ENABLED: "true"
      JAEGER_UDP_HOST: "jaeger"
      JAEGER_UDP_PORT: 6831
    ports:
      - 8090:4500
    networks:
      - private

networks:
  private:
    name: private
    driver: bridge # for local (use overlay for swarm multi nodes)
