version: '3.3'
services:

  api:
    image: immo:quarkus-jvm
    ports:
      - 8080:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/ezloc
      QUARKUS_HTTP_PORT: 8080
    networks:
      - immo
    depends_on:
      - postgres

  api-native:
    image: immo:quarkus-native
    ports:
      - 8081:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/ezloc
      QUARKUS_HTTP_PORT: 8080
      quarkus.native.native-image-xmx: 16G
    networks:
      - immo
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ezloc
      POSTGRES_USER: hsedjame
      POSTGRES_PASSWORD: hsedjame
    hostname: postgres
    networks:
      - immo

volumes:
  postgres_data:

networks:
  immo:
