version: 2.1

orbs:
  slack: circleci/slack@4.1
  maven: circleci/maven@1.1
                 
workflows:
  build:
    jobs:
      - build
      - docker_push_registry
  maven_test:
    jobs:
      - maven/test

jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application with Maven
      # - run: mvn clean package

      # build the application image
      - run: docker build -t ${DOCKER_REGISTRY}/ezloc-immo:$CIRCLE_BRANCH .   

      # notify to slack
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - slack/notify:
          branch_pattern: develop
          event: fail
          mentions: '@ntran'
          template: basic_fail_1

  push_registry:
    executor: docker
    steps:
      - run:
          name: Push docker image to registry
          command: |
              docker login -u ${DOCKER_REGISTRY_USER_NAME} -p ${DOCKER_REGISTRY_USER_PASSWORD}
              docker push ${DOCKER_REGISTRY}/ezloc-immo:$CIRCLE_BRANCH
