server:
  port: 4500

  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:immodb

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update

  liquibase:
    enabled: false

springdoc:
  api-docs:
    # http://localhost:8080/swagger-ui.html
    # http://localhost:8080/api-docs/
    # http://localhost:8080/v3/api-docs.yaml
    path: /api-docs
