# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Immo Microservice CI & CD pipeline 

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  release:
    types: [created]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-lastest, macOS-latest]
    permissions:
      contents: read
      packages: write

    steps:
    
    # Checkout sources project
    - uses: actions/checkout@v2
    
    # Setting up Java version
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    # Call Maven to build project
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Deploy the artefact with Maven
    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
  
  
  docker:
    
    runs-on: ubuntu-latest

    steps: # Build and push Docker image to Docker Registry
    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ntdtfr/ezloc-immo:latest 
        
#  publish:
    
#    needs: build
    
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-lastest, macOS-latest]
